import type { SampleProfile, InterestProfile, RecommendedVideo } from "./types";

export const SAMPLE_PROFILES: SampleProfile[] = [
  {
    id: "tech_innovator",
    username: "demo_ai_builder",
    displayName: "Sora Tanaka",
    bio: "Building AI products for real-world impact. Ex-startup founder. Passionate about the intersection of technology and society.",
    label: "AI・テクノロジー",
    description: "AI・スタートアップ・テクノロジーに関心がある人物",
    posts: [
      "生成AIの進化が想像以上に速い。今年はエージェント型AIが事業に組み込まれる転換点になりそう。",
      "スタートアップが本当に解くべき問題は何か。技術より先に、社会課題を深掘りすることが大切だと思う。",
      "GPT-4oのマルチモーダル機能を試した。音声と画像を同時に扱えるのは、プロダクト設計の幅を広げる。",
      "AIエージェントが自律的にタスクをこなす未来は、想像以上に近い。Devin、AutoGPTあたりを毎日追ってる。",
      "海外のVCが生成AIに投資する理由を分析してみた。コスト削減より、新規市場創出への期待が大きい。",
      "社会実装という観点でAIを見ると、技術の完成度より普及経路の設計のほうが難しい。",
      "OpenAIとGoogleのAI競争、2025年は面白いフェーズに入ると思う。",
      "ProductHuntで毎日新しいAIツールが出てくるのを眺めるのが習慣になった。",
      "スタートアップのピッチで一番響くのは、なぜ今この問題なのか、という問い。",
      "Claude 3.5のコーディング能力、マジで実用的になってきた。",
    ],
  },
  {
    id: "art_architect",
    username: "demo_art_design",
    displayName: "Hana Mizushima",
    bio: "Architecture, art, and the poetry of space. Exploring how design shapes human experience.",
    label: "アート・建築・デザイン",
    description: "アート・建築・デザインに関心がある人物",
    posts: [
      "ザハ・ハディドの建築を再訪。流動的な空間が人の動きをどう誘導するか、改めて考えさせられた。",
      "デザインは問題解決ではなく、問題の発見だと思う。",
      "今週はバウハウス100年展のカタログを読んでいた。機能と美しさの統合という概念が今でも新鮮。",
      "東京の路地裏の美しさ、誰かと共有したい。計画されていない空間の豊かさがある。",
      "アートディレクションの仕事で、余白の意味を改めて学んでいる。",
      "隈研吾の木材の使い方、素材と文化の融合という点で世界に通じる言語だと感じる。",
      "ミュージアムの展示デザインは、動線設計が体験の80%を決める。",
      "色彩理論を学び直している。デジタルとフィジカルで全く違う制約がある。",
      "自然素材と現代建築の組み合わせが好きで、北欧の事例をよく参照する。",
      "写真と建築の共通点は、フレームの中に何を入れ、何を除くか、という選択だと思う。",
    ],
  },
  {
    id: "eco_activist",
    username: "demo_eco_local",
    displayName: "Kaito Mori",
    bio: "Biologist & local community builder. Thinking about ecosystems, both natural and human.",
    label: "環境・生態・地域社会",
    description: "環境・生物・地域社会に関心がある人物",
    posts: [
      "地域の川で今年もホタルが飛んでいた。環境指標として、これほど分かりやすいものはない。",
      "生物多様性の損失は、気候変動と並ぶ地球規模の危機だと思う。でも報道は少ない。",
      "里山の管理が途絶えると、生態系が単純化される。人の関与が必要な自然もある。",
      "コミュニティガーデンを立ち上げた。食、生態、交流が一つの場所でつながるのが面白い。",
      "都市の緑化は見た目だけでなく、生物の移動経路として機能する必要がある。",
      "在来種と外来種の問題を地域住民に伝えるのが難しい。科学と生活感覚の橋渡しが必要。",
      "昆虫食に関心が出てきた。タンパク源の多様化という点で真剣に考えるべき時代だと思う。",
      "地域の祭りと生態系の関係、面白い論文を読んだ。文化的慣行が森を守る事例がある。",
      "再生可能エネルギーの導入で、地元の生態系への影響をどう最小化するか議論が必要。",
      "子どもたちに虫の名前を教えると、自然への親近感が一気に変わる。",
    ],
  },
];

export const SAMPLE_INTEREST_PROFILES: Record<string, InterestProfile> = {
  tech_innovator: {
    displayName: "Sora Tanaka",
    summary: "AIとスタートアップの社会実装に関心を持ち、技術の事業性と社会インパクトの両面から評価する人物",
    interests: ["生成AI", "スタートアップ", "プロダクト開発", "社会実装", "海外テクノロジー動向"],
    perspective:
      "新しい技術を、事業性と社会への影響の両面から評価する傾向があります。技術の完成度よりも、普及経路と社会実装の難しさに注目しています。",
    keywords: ["AI agent", "startup", "product development", "social impact"],
    youtubeSearchQueries: [
      "AI agents startup practical applications 2024",
      "future of software development AI impact",
      "technology social impact documentary",
      "generative AI business use cases",
      "startup founder insights fundraising",
    ],
  },
  art_architect: {
    displayName: "Hana Mizushima",
    summary: "建築・アート・デザインを通じて人間の空間体験を探求し、機能と美の統合を追求する人物",
    interests: ["建築デザイン", "現代アート", "空間体験", "バウハウス", "都市景観"],
    perspective:
      "デザインを問題解決ではなく問題の発見と捉え、余白・素材・動線といった非言語的な要素に強い関心を持っています。",
    keywords: ["architecture", "art direction", "spatial design", "Bauhaus", "urban space"],
    youtubeSearchQueries: [
      "contemporary architecture documentary Zaha Hadid",
      "Bauhaus design philosophy modern application",
      "urban space design human experience",
      "Japanese architecture wood natural materials",
      "museum exhibition design spatial storytelling",
    ],
  },
  eco_activist: {
    displayName: "Kaito Mori",
    summary: "生物学的視点と地域社会への関与から、自然生態系と人間コミュニティの共生を模索する人物",
    interests: ["生物多様性", "里山管理", "コミュニティ形成", "環境教育", "地域エコシステム"],
    perspective:
      "科学的知識と地域住民の生活感覚を橋渡しすることに関心を持ち、自然環境への関与が必要な場合もあると認識しています。",
    keywords: ["biodiversity", "ecosystem", "community", "satoyama", "environmental education"],
    youtubeSearchQueries: [
      "biodiversity loss ecosystem collapse documentary",
      "satoyama landscape traditional Japanese land management",
      "community garden urban ecosystem",
      "insect ecology food system future protein",
      "rewilding nature restoration case study",
    ],
  },
};

export const FEATURED_INTEREST_PROFILES: Record<string, InterestProfile> = {
  "10000nabe": {
    displayName: "渡辺銀次",
    summary: "吉本所属のお笑いコンビ「ドンデコルテ」として、地方文化・ご当地グルメ・地産地消に強い愛着を持つコメディアン",
    interests: ["お笑い・コメディ", "地方文化", "食文化・グルメ", "地産地消", "ローカルコミュニティ"],
    perspective:
      "全国各地の食と文化を笑いとともに発信することで、地域の魅力を掘り起こす視点を持っています。都市目線ではなく、現地の生活感覚を大切にしています。",
    keywords: ["Japanese comedy", "regional food", "local culture", "stand-up", "gourmet"],
    youtubeSearchQueries: [
      "日本 ご当地グルメ 食文化 ドキュメンタリー",
      "Japanese regional food local culture documentary",
      "stand-up comedy Japanese comedian variety",
      "地方 食材 地産地消 料理",
      "manzai rakugo Japanese comedy performance",
    ],
  },
  ochyai: {
    displayName: "落合陽一",
    summary: "メディアアーティストかつ筑波大学准教授として、デジタルネイチャーの思想でテクノロジーとアートと自然の境界を溶かす研究者・表現者",
    interests: ["メディアアート", "デジタルネイチャー", "AI・テクノロジー", "インタラクティブアート", "社会と技術の哲学"],
    perspective:
      "「デジタルと自然は対立しない」という思想のもと、計算機と物質の融合を探求しています。研究・アート・ビジネスの境界を超えた活動を続けています。",
    keywords: ["media art", "digital nature", "AI art", "interactive installation", "technology philosophy"],
    youtubeSearchQueries: [
      "media art digital nature technology installation",
      "AI art generative creative machine learning",
      "Japanese contemporary art technology exhibition",
      "digital fabrication computational design",
      "technology philosophy future society humanity",
    ],
  },
  shi3z: {
    displayName: "清水亮",
    summary: "AI研究者・起業家として日本のソフトウェア・AI開発シーンを牽引し、生成AIと実装技術の最前線を発信するエンジニア経営者",
    interests: ["AI・機械学習", "ソフトウェアエンジニアリング", "起業・スタートアップ", "生成AI実装", "日本のテック産業"],
    perspective:
      "技術の本質を理解しつつ事業化する実践的な視点を持ち、AIの社会実装において先駆者的な役割を担っています。コードを書き続ける現役エンジニアとしての言葉が持ち味です。",
    keywords: ["generative AI", "software engineering", "deep learning", "startup Japan", "LLM implementation"],
    youtubeSearchQueries: [
      "generative AI LLM implementation engineering",
      "deep learning machine learning practical tutorial",
      "Japanese tech entrepreneur startup AI",
      "software architecture system design engineering",
      "AI startup business model technology innovation",
    ],
  },
};

export const SAMPLE_VIDEOS: RecommendedVideo[] = [
  // tech_innovator videos
  {
    videoId: "sample_tech_1",
    title: "The AI Revolution: How Generative AI is Transforming Businesses",
    description: "A deep dive into how companies are using generative AI to create new business models.",
    thumbnail: "https://img.youtube.com/vi/aircAruvnKk/mqdefault.jpg",
    channelTitle: "TED",
    publishedAt: "2024-03-15T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=AI+generative+business+transformation",
    category: "core",
    reason:
      "この人物は生成AIの事業活用に強い関心を示しています。この動画はAI技術の社会実装と事業変革を具体的に解説しており、関心に直接合致します。",
    relevanceScore: 95,
    serendipityScore: 30,
  },
  {
    videoId: "sample_tech_2",
    title: "How AI Agents Will Change the Way We Work",
    description: "Exploring the future of autonomous AI agents in professional environments.",
    thumbnail: "https://img.youtube.com/vi/l0GgTNS_-aI/mqdefault.jpg",
    channelTitle: "Stanford University",
    publishedAt: "2024-05-20T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=AI+agents+future+work+autonomous",
    category: "core",
    reason:
      "AIエージェントへの関心が投稿から明確に読み取れます。スタンフォード大学の研究者が自律型AIエージェントの未来を解説しており、技術と社会実装の両面を扱っています。",
    relevanceScore: 92,
    serendipityScore: 25,
  },
  {
    videoId: "sample_tech_3",
    title: "Why Most Startups Fail: Lessons from 1000+ Founders",
    description: "Analyzing patterns in startup failure and what the most successful founders did differently.",
    thumbnail: "https://img.youtube.com/vi/MT7qH1b1Grs/mqdefault.jpg",
    channelTitle: "Y Combinator",
    publishedAt: "2024-01-10T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=startup+failure+lessons+YCombinator",
    category: "adjacent",
    reason:
      "スタートアップへの関心が高い人物に対し、起業家の視点を深める内容です。技術よりも事業モデルと組織に焦点を当てており、視野を広げます。",
    relevanceScore: 78,
    serendipityScore: 55,
  },
  {
    videoId: "sample_tech_4",
    title: "The Case Against Technology Optimism",
    description: "A critical examination of how technology sometimes creates more problems than it solves.",
    thumbnail: "https://img.youtube.com/vi/P18UI35s9qU/mqdefault.jpg",
    channelTitle: "Big Think",
    publishedAt: "2024-02-28T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=technology+pessimism+critique+society",
    category: "opposite",
    reason:
      "テクノロジー楽観主義とは対立する視点を提供します。社会実装に関心を持つ人物にとって、技術批判の視点は盲点を補う重要な視野となります。",
    relevanceScore: 62,
    serendipityScore: 88,
  },

  {
    videoId: "sample_tech_5",
    title: "Building AI Products: From Prototype to Production",
    description: "Engineering leaders share how to scale AI features in real products, including pitfalls and best practices.",
    thumbnail: "https://img.youtube.com/vi/VMj-3S1tku0/mqdefault.jpg",
    channelTitle: "Andrej Karpathy",
    publishedAt: "2024-06-10T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=building+AI+products+production+engineering",
    category: "core",
    reason: "AIプロダクト開発の実践的な視点を提供します。プロトタイプから本番運用まで、現場エンジニアが語るAI実装のリアルが、この人物の社会実装への関心に合致します。",
    relevanceScore: 90,
    serendipityScore: 28,
  },
  {
    videoId: "sample_tech_6",
    title: "Japan's Tech Startup Scene: Why Now Is the Moment",
    description: "Investors and founders discuss the emerging opportunities in Japan's startup ecosystem.",
    thumbnail: "https://img.youtube.com/vi/HW29067qVWk/mqdefault.jpg",
    channelTitle: "SoftBank Vision Fund",
    publishedAt: "2024-04-01T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=Japan+startup+ecosystem+opportunity+2024",
    category: "core",
    reason: "日本のスタートアップエコシステムに関する投資家・起業家の視点。海外VCのAI投資動向を追う人物に、国内文脈を加える補完的な情報です。",
    relevanceScore: 86,
    serendipityScore: 35,
  },
  {
    videoId: "sample_tech_7",
    title: "The State of LLMs: What Every Product Builder Needs to Know",
    description: "A technical overview of the current landscape of large language models and their practical applications.",
    thumbnail: "https://img.youtube.com/vi/zjkBMFhNj_g/mqdefault.jpg",
    channelTitle: "Andrej Karpathy",
    publishedAt: "2024-07-20T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=LLM+overview+product+builder+2024",
    category: "core",
    reason: "LLMの現状を体系的に整理した動画。Claude・GPT-4oを日常的に追う人物にとって、技術全体を俯瞰する視点として価値があります。",
    relevanceScore: 89,
    serendipityScore: 22,
  },
  {
    videoId: "sample_tech_8",
    title: "How to Raise a Series A in 2024: VC Secrets Revealed",
    description: "Top venture capitalists explain what they look for in Series A companies and how to stand out.",
    thumbnail: "https://img.youtube.com/vi/TSts0nikFk8/mqdefault.jpg",
    channelTitle: "Y Combinator",
    publishedAt: "2024-03-05T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=Series+A+fundraising+2024+VC+tips",
    category: "adjacent",
    reason: "AI投資動向を分析する人物に、資金調達の実務側からの視点を提供します。技術から事業への橋渡しとして有益な周辺領域です。",
    relevanceScore: 74,
    serendipityScore: 48,
  },
  {
    videoId: "sample_tech_9",
    title: "Company Culture at Scale: Lessons from Fast-Growing Tech Companies",
    description: "How engineering culture shapes product quality and team performance at leading tech companies.",
    thumbnail: "https://img.youtube.com/vi/RBH1hNz9Wms/mqdefault.jpg",
    channelTitle: "First Round Capital",
    publishedAt: "2024-02-18T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=startup+engineering+culture+scale+lessons",
    category: "adjacent",
    reason: "スタートアップが本質的な問題を解くには組織文化が鍵という視点から、チームビルディングの隣接領域を探索します。",
    relevanceScore: 70,
    serendipityScore: 52,
  },
  {
    videoId: "sample_tech_10",
    title: "The Dark Side of AI: Surveillance, Bias, and Corporate Power",
    description: "Critics examine how AI systems reinforce inequality and enable new forms of surveillance capitalism.",
    thumbnail: "https://img.youtube.com/vi/PacUOh7QQIU/mqdefault.jpg",
    channelTitle: "The Guardian",
    publishedAt: "2024-05-12T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=AI+surveillance+bias+critique+corporate",
    category: "opposite",
    reason: "AI楽観主義に対するカウンターとして、テクノロジーが権力構造をどう強化するかを問います。社会実装を考えるうえで欠かせない批判的視点です。",
    relevanceScore: 55,
    serendipityScore: 90,
  },
  {
    videoId: "sample_tech_11",
    title: "Slow Down: Why Deliberate Technology Adoption Wins",
    description: "Case studies showing that organizations who adopt technology slowly and deliberately outperform fast movers.",
    thumbnail: "https://img.youtube.com/vi/EumXak7TVzc/mqdefault.jpg",
    channelTitle: "Harvard Business Review",
    publishedAt: "2024-01-08T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=slow+technology+adoption+deliberate+strategy",
    category: "opposite",
    reason: "「速いAIの進化を追う」姿勢とは正反対に、意図的な技術採用の遅さが競争優位になると主張します。異なる戦略的視点として思考の幅を広げます。",
    relevanceScore: 48,
    serendipityScore: 87,
  },

  // art_architect videos
  {
    videoId: "sample_art_1",
    title: "Zaha Hadid: The Architecture of Motion",
    description: "Exploring the revolutionary architectural philosophy of Zaha Hadid and her lasting legacy.",
    thumbnail: "https://img.youtube.com/vi/nHLhgCfODYI/mqdefault.jpg",
    channelTitle: "Architectural Digest",
    publishedAt: "2024-04-05T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=Zaha+Hadid+architecture+documentary",
    category: "core",
    reason:
      "ザハ・ハディドの建築への言及が投稿に見られます。この動画は流動的空間の設計哲学を詳細に解説しており、人物の関心に直接対応しています。",
    relevanceScore: 96,
    serendipityScore: 22,
  },
  {
    videoId: "sample_art_2",
    title: "Bauhaus: Art as Life - Full Documentary",
    description: "A comprehensive look at the Bauhaus movement and its influence on modern design.",
    thumbnail: "https://img.youtube.com/vi/fXIqKiF7fBU/mqdefault.jpg",
    channelTitle: "DW Documentary",
    publishedAt: "2024-01-22T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=Bauhaus+documentary+design+art+history",
    category: "core",
    reason:
      "バウハウスへの強い関心が投稿から読み取れます。機能と美の統合というテーマを歴史的視点から解説するドキュメンタリーです。",
    relevanceScore: 94,
    serendipityScore: 28,
  },
  {
    videoId: "sample_art_3",
    title: "How Music Shapes Architecture (and Vice Versa)",
    description: "The surprising connections between sound and space in architectural design.",
    thumbnail: "https://img.youtube.com/vi/xHVLMfMk0vQ/mqdefault.jpg",
    channelTitle: "The B1M",
    publishedAt: "2024-03-08T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=music+architecture+sound+space+design",
    category: "adjacent",
    reason:
      "空間体験への関心を音楽という別の感覚軸から探求します。建築とデザインの視野を聴覚的な次元に広げる一歩踏み出した内容です。",
    relevanceScore: 72,
    serendipityScore: 70,
  },
  {
    videoId: "sample_art_4",
    title: "Why Brutalism is Coming Back",
    description: "The controversial architectural style that was once despised is now experiencing a revival.",
    thumbnail: "https://img.youtube.com/vi/cXfU8LcHqTs/mqdefault.jpg",
    channelTitle: "Vox",
    publishedAt: "2024-02-14T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=brutalism+architecture+revival+why",
    category: "opposite",
    reason:
      "有機的・流動的な建築を好む傾向とは対照的な、コンクリートの力強さを主張するブルータリズムの視点を提供します。",
    relevanceScore: 58,
    serendipityScore: 85,
  },

  {
    videoId: "sample_art_5",
    title: "Kengo Kuma: Erasing Architecture",
    description: "The Japanese architect discusses his philosophy of hiding buildings in nature and using local materials.",
    thumbnail: "https://img.youtube.com/vi/pvn3Z6o5glw/mqdefault.jpg",
    channelTitle: "Dezeen",
    publishedAt: "2024-03-22T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=Kengo+Kuma+architecture+wood+nature+documentary",
    category: "core",
    reason: "隈研吾の木材と文化融合への言及が投稿にあります。「建築を消す」という彼の哲学を深く掘り下げ、素材と空間の関係を探求する内容です。",
    relevanceScore: 93,
    serendipityScore: 25,
  },
  {
    videoId: "sample_art_6",
    title: "The Hidden Grammar of Cities: How Urban Space Shapes Behavior",
    description: "Urban designers and sociologists examine how city layouts influence how people live and interact.",
    thumbnail: "https://img.youtube.com/vi/V76SBtPWHGI/mqdefault.jpg",
    channelTitle: "Bloomberg CityLab",
    publishedAt: "2024-04-30T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=urban+space+design+behavior+city+documentary",
    category: "core",
    reason: "東京の路地裏の空間的豊かさへの関心から、都市空間が人の行動に与える影響を社会学的・設計的視点で探求します。",
    relevanceScore: 91,
    serendipityScore: 30,
  },
  {
    videoId: "sample_art_7",
    title: "Color Theory: Understanding the Language of Visual Design",
    description: "A masterclass on how color communicates, influences emotion, and creates meaning in art and design.",
    thumbnail: "https://img.youtube.com/vi/0LoXaKCGkh4/mqdefault.jpg",
    channelTitle: "Adobe",
    publishedAt: "2024-02-10T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=color+theory+masterclass+visual+design+digital",
    category: "core",
    reason: "色彩理論を学び直しているという投稿を踏まえ、デジタルとフィジカルの違いも含めて色彩の言語を体系的に解説するマスタークラスです。",
    relevanceScore: 88,
    serendipityScore: 20,
  },
  {
    videoId: "sample_art_8",
    title: "Photography and Space: Framing the Invisible",
    description: "How photographers compose images to convey architectural space, light, and human emotion.",
    thumbnail: "https://img.youtube.com/vi/7ZVyNjKSr0M/mqdefault.jpg",
    channelTitle: "The Phoblographer",
    publishedAt: "2024-05-08T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=architecture+photography+framing+space+light",
    category: "adjacent",
    reason: "写真と建築の共通性（フレームの内外の選択）への言及を踏まえ、空間を視覚的に切り取る行為の探求へと視野を広げます。",
    relevanceScore: 76,
    serendipityScore: 60,
  },
  {
    videoId: "sample_art_9",
    title: "The Neuroscience of Space: How Design Affects the Brain",
    description: "Scientists explain how architectural choices—light, ceiling height, curves—alter cognition and mood.",
    thumbnail: "https://img.youtube.com/vi/Ke90Tje7VS0/mqdefault.jpg",
    channelTitle: "TED",
    publishedAt: "2024-01-15T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=neuroscience+space+architecture+brain+design",
    category: "adjacent",
    reason: "空間体験への強い関心を神経科学という別領域から掘り下げます。デザインが脳に与える影響を科学的に解説し、設計思想に新たな視点を加えます。",
    relevanceScore: 73,
    serendipityScore: 65,
  },
  {
    videoId: "sample_art_10",
    title: "Why Plain Design Always Wins: The Case for Radical Simplicity",
    description: "Designers argue that the most enduring work strips everything away to its barest, most honest form.",
    thumbnail: "https://img.youtube.com/vi/obAuNaf6evo/mqdefault.jpg",
    channelTitle: "The Futur",
    publishedAt: "2024-06-02T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=minimalism+design+radical+simplicity+wins",
    category: "opposite",
    reason: "余白・素材の複雑な組み合わせを探求する姿勢とは対照的に、極限の簡素さこそが最も強いデザインだという立場を提示します。",
    relevanceScore: 55,
    serendipityScore: 82,
  },
  {
    videoId: "sample_art_11",
    title: "Street Art vs. Fine Art: Does Context Create Legitimacy?",
    description: "Critics and artists debate whether art's value comes from institutional approval or cultural resonance.",
    thumbnail: "https://img.youtube.com/vi/9GRwJFYLiPU/mqdefault.jpg",
    channelTitle: "Vice",
    publishedAt: "2024-03-14T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=street+art+fine+art+legitimacy+debate",
    category: "opposite",
    reason: "美術館の展示設計を手がける人物に、アートの価値が制度から生まれるのか文化的共鳴から生まれるのかという根本的な問いを投げかけます。",
    relevanceScore: 50,
    serendipityScore: 88,
  },

  // eco_activist videos
  {
    videoId: "sample_eco_1",
    title: "The Sixth Mass Extinction: What We Can Still Do",
    description: "Scientists explain the current biodiversity crisis and pathways to prevention.",
    thumbnail: "https://img.youtube.com/vi/B4H7QuBWZKY/mqdefault.jpg",
    channelTitle: "PBS Terra",
    publishedAt: "2024-04-18T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=sixth+mass+extinction+biodiversity+documentary",
    category: "core",
    reason:
      "生物多様性の損失への強い関心が投稿から読み取れます。科学者が解説する絶滅危機の実態と対策は、この人物の関心の核心に触れます。",
    relevanceScore: 97,
    serendipityScore: 20,
  },
  {
    videoId: "sample_eco_2",
    title: "Japan's Satoyama: Nature's Secret Keepers",
    description: "How traditional Japanese countryside landscapes became models for biodiversity conservation.",
    thumbnail: "https://img.youtube.com/vi/7Hj4KFnRWxk/mqdefault.jpg",
    channelTitle: "NHK World",
    publishedAt: "2024-02-02T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=satoyama+Japan+biodiversity+traditional+landscape",
    category: "core",
    reason:
      "里山管理への言及が複数の投稿に見られます。日本の伝統的な里山管理が生物多様性保全のモデルになっている事例を紹介する動画です。",
    relevanceScore: 93,
    serendipityScore: 32,
  },
  {
    videoId: "sample_eco_3",
    title: "Urban Farming Revolution: Cities Growing Their Own Food",
    description: "How urban agriculture is transforming city spaces and local food systems.",
    thumbnail: "https://img.youtube.com/vi/mHLnv5gM3HA/mqdefault.jpg",
    channelTitle: "Vice",
    publishedAt: "2024-03-25T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=urban+farming+city+food+community",
    category: "adjacent",
    reason:
      "コミュニティガーデンへの取り組みから、都市農業という隣接領域に視野を広げます。食・生態・コミュニティの交差点への関心に応える内容です。",
    relevanceScore: 80,
    serendipityScore: 52,
  },
  {
    videoId: "sample_eco_4",
    title: "The Case for Nuclear Power in a Climate Emergency",
    description: "Environmental scientists make the controversial argument for nuclear energy as a green solution.",
    thumbnail: "https://img.youtube.com/vi/N-yALPEpV4w/mqdefault.jpg",
    channelTitle: "DW Documentary",
    publishedAt: "2024-01-30T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=nuclear+power+climate+environment+case+for",
    category: "opposite",
    reason:
      "再生可能エネルギーへの関心とは異なる視点として、原子力エネルギーを環境解決策として提示します。エネルギー選択の多様な視点を得られます。",
    relevanceScore: 55,
    serendipityScore: 90,
  },
  {
    videoId: "sample_eco_5",
    title: "The Secret Life of Rivers: Ecology of Flowing Water",
    description: "Biologists reveal the hidden complexity of river ecosystems and what losing them means for biodiversity.",
    thumbnail: "https://img.youtube.com/vi/5lqUbqCVxdI/mqdefault.jpg",
    channelTitle: "PBS Terra",
    publishedAt: "2024-05-05T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=river+ecology+biodiversity+documentary+biology",
    category: "core",
    reason: "地域の川でホタルを観察するという投稿を踏まえ、河川生態系の複雑さと喪失の意味を科学的に解説します。環境指標への関心と直接つながります。",
    relevanceScore: 94,
    serendipityScore: 22,
  },
  {
    videoId: "sample_eco_6",
    title: "The World of Insects: Why They Matter More Than You Think",
    description: "Entomologists explain insects' critical role in ecosystems and the alarming decline happening globally.",
    thumbnail: "https://img.youtube.com/vi/GgPGFHy9bIg/mqdefault.jpg",
    channelTitle: "SciShow",
    publishedAt: "2024-04-25T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=insects+ecology+importance+decline+biodiversity",
    category: "core",
    reason: "子どもに虫の名前を教えるという投稿や昆虫食への関心から、昆虫が生態系に果たす役割の重要性を科学的に探求する動画です。",
    relevanceScore: 91,
    serendipityScore: 30,
  },
  {
    videoId: "sample_eco_7",
    title: "How Indigenous Land Management Saves Ecosystems",
    description: "Researchers document how traditional indigenous practices maintain biodiversity better than modern approaches.",
    thumbnail: "https://img.youtube.com/vi/QLDZkMDPCRI/mqdefault.jpg",
    channelTitle: "Mongabay",
    publishedAt: "2024-03-18T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=indigenous+land+management+biodiversity+traditional+knowledge",
    category: "core",
    reason: "文化的慣行が森を守る事例への関心と合致します。先住民の土地管理が現代的手法より生態系を保全できるという研究を紹介します。",
    relevanceScore: 90,
    serendipityScore: 35,
  },
  {
    videoId: "sample_eco_8",
    title: "The Future of Food: Can Insects Feed the World?",
    description: "Chefs, scientists, and entrepreneurs explore the potential and challenges of insect-based foods.",
    thumbnail: "https://img.youtube.com/vi/br62tpuMBj4/mqdefault.jpg",
    channelTitle: "Bloomberg Quicktake",
    publishedAt: "2024-06-15T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=insect+food+protein+future+sustainability",
    category: "adjacent",
    reason: "昆虫食への真剣な関心を、シェフ・科学者・起業家の視点で掘り下げます。タンパク源の多様化という問いに対する実践的かつ多角的なアプローチです。",
    relevanceScore: 82,
    serendipityScore: 55,
  },
  {
    videoId: "sample_eco_9",
    title: "Rewilding: Can We Let Nature Heal Itself?",
    description: "The story of rewilding projects across Europe and what happens when humans step back from the land.",
    thumbnail: "https://img.youtube.com/vi/0dIR5ksiAmI/mqdefault.jpg",
    channelTitle: "DW Documentary",
    publishedAt: "2024-02-25T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=rewilding+Europe+nature+restoration+documentary",
    category: "adjacent",
    reason: "人の関与が必要な自然がある一方で、人が退くことで自然が回復するリワイルディングの事例を探求します。里山管理とは対になる視点です。",
    relevanceScore: 79,
    serendipityScore: 50,
  },
  {
    videoId: "sample_eco_10",
    title: "Industrial Agriculture's Hidden Environmental Benefits",
    description: "Agricultural economists argue that intensive farming on less land preserves more wild habitat overall.",
    thumbnail: "https://img.youtube.com/vi/MsTmXQpJZao/mqdefault.jpg",
    channelTitle: "Our World in Data",
    publishedAt: "2024-01-20T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=industrial+agriculture+environment+land+use+efficiency",
    category: "opposite",
    reason: "有機農業・在来種保護の視点とは逆に、集約農業が野生地保全に貢献するという経済学的主張を紹介します。エビデンスに基づく逆説的な視点です。",
    relevanceScore: 52,
    serendipityScore: 92,
  },
  {
    videoId: "sample_eco_11",
    title: "The Business Case for Biodiversity: Nature as Capital",
    description: "Finance leaders explain how ecosystem services are being monetized and why markets may save nature.",
    thumbnail: "https://img.youtube.com/vi/zz7TTHSB2Ss/mqdefault.jpg",
    channelTitle: "World Economic Forum",
    publishedAt: "2024-04-08T00:00:00Z",
    url: "https://www.youtube.com/results?search_query=biodiversity+business+natural+capital+finance",
    category: "opposite",
    reason: "生態系保全を科学・地域から語る人物に対し、自然を資本として市場が保護するという異なる価値観を提示します。対立軸として思考を刺激します。",
    relevanceScore: 48,
    serendipityScore: 89,
  },
];

export function getSampleVideosForProfile(profileId: string): RecommendedVideo[] {
  const profileMap: Record<string, string[]> = {
    tech_innovator: [
      "sample_tech_1", "sample_tech_2", "sample_tech_5", "sample_tech_6", "sample_tech_7",
      "sample_tech_3", "sample_tech_8", "sample_tech_9",
      "sample_tech_4", "sample_tech_10", "sample_tech_11",
    ],
    art_architect: [
      "sample_art_1", "sample_art_2", "sample_art_5", "sample_art_6", "sample_art_7",
      "sample_art_3", "sample_art_8", "sample_art_9",
      "sample_art_4", "sample_art_10", "sample_art_11",
    ],
    eco_activist: [
      "sample_eco_1", "sample_eco_2", "sample_eco_5", "sample_eco_6", "sample_eco_7",
      "sample_eco_3", "sample_eco_8", "sample_eco_9",
      "sample_eco_4", "sample_eco_10", "sample_eco_11",
    ],
  };

  const ids = profileMap[profileId] ?? profileMap["tech_innovator"];
  return SAMPLE_VIDEOS.filter((v) => ids.includes(v.videoId));
}
